[env]
TERM = "xterm-256color"

[cursor]
style = { shape = "Block", blinking = "Always" }

[window]
opacity = 0.97
padding.x = 4
padding.y = 4

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[font]
normal = { family = "BerkeleyMono Nerd Font", style = "Regular" }
bold = { family = "BerkeleyMono Nerd Font", style = "Bold" }
italic = { family = "BerkeleyMono Nerd Font", style = "Italic" }
size = 13

[colors]
[colors.primary]
background = '#181616'
foreground = '#c5c9c5'

[colors.normal]
black = '#0d0c0c'
blue = '#8ba4b0'
cyan = '#8ea4a2'
green = '#8a9a7b'
magenta = '#a292a3'
red = '#c4746e'
white = '#C8C093'
yellow = '#c4b28a'

[colors.bright]
black = '#a6a69c'
blue = '#7FB4CA'
cyan = '#7AA89F'
green = '#87a987'
magenta = '#938AA9'
red = '#E46876'
white = '#c5c9c5'
yellow = '#E6C384'

[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'

[[colors.indexed_colors]]
index = 16
color = '#ffa066'

[[colors.indexed_colors]]
index = 17
color = '#ff5d62'
# [colors]
# [colors.primary]
# background = '#2d353b'
# foreground = '#d3c6aa'
#
# [colors.normal]
# black = '#475258'
# red = '#e67e80'
# green = '#a7c080'
# yellow = '#dbbc7f'
# blue = '#7fbbb3'
# magenta = '#d699b6'
# cyan = '#83c092'
# white = '#d3c6aa'
#
# [colors.bright]
# black = '#475258'
# red = '#e67e80'
# green = '#a7c080'
# yellow = '#dbbc7f'
# blue = '#7fbbb3'
# magenta = '#d699b6'
# cyan = '#83c092'
# white = '#d3c6aa'
