exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE QT_QPA_PLATFORMTHEME
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE QT_QPA_PLATFORMTHEME
exec-once = ksecretd

exec-once = waybar
exec-once = mako
exec-once = walker --gapplication-service
exec-once = /usr/libexec/kf6/polkit-kde-authentication-agent-1
exec-once = nm-applet --indicator
exec-once = /home/ibanks/.local/bin/winboat-helper

exec-once = hyprpaper
