# exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE QT_QPA_PLATFORMTHEME
# exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE QT_QPA_PLATFORMTHEME
# exec-once = ksecretd

exec-once = waybar
exec-once = mako
exec-once = systemctl --user start elephant
exec-once = walker --gapplication-service
exec-once = systemctl --user start hyprpolkitagent
exec-once = nm-applet --indicator
# exec-once = flatpak run com.github.wwmm.easyeffects
exec-once = flatpak run com.github.wwmm.easyeffects --service-mode --hide-window
exec-once = kdeconnect
exec-once = /home/ibanks/dotfiles/hypr/local/bin/rbw-unlock-elephant
exec-once = [workspace 2 silent] vivaldi-stable

# default app layout
exec-once = [workspace 1 silent] ghostty

exec-once = hyprctl dispatch workspace 1
