$font = Segoe UI

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = smooth, 0.2, 0.9, 0.1, 1.0
    animation = fadeIn, 1, 5, smooth
    animation = fadeOut, 1, 5, smooth
    animation = inputFieldDots, 1, 3, smooth
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 6
    noise = 0.01
    brightness = 0.74
}

input-field {
    monitor =
    size = 340, 58
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(4385beee)
    inner_color = rgba(1c1b1af0)
    font_color = rgb(206, 205, 195)
    fade_on_empty = false
    placeholder_text = Enter password
    fail_text = $PAMFAIL
    fail_color = rgba(d14d41ee)
    check_color = rgba(879a39ee)
    rounding = 16
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 72
    font_family = $font
    color = rgb(206, 205, 195)
    position = 0, 110
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %B %d"
    font_size = 20
    font_family = $font
    color = rgb(135, 133, 128)
    position = 0, 55
    halign = center
    valign = center
}
