$wallpaper = ~/Pictures/wallpapers/mylene2401-umbrella-4692572.jpg

wallpaper {
  monitor = DP-1
  path = $wallpaper
}

wallpaper {
  monitor = DP-2
  path = $wallpaper
}

wallpaper {
  monitor = DP-3
  path = $wallpaper
}
