input {
    kb_layout = us
    follow_mouse = 0
    numlock_by_default = true
    repeat_delay = 250
    repeat_rate = 20

    touchpad {
        natural_scroll = true
        tap-to-click = true
        disable_while_typing = true
    }

    sensitivity = 0
}

cursor {
    no_warps = true
}

gestures {
  # workspace_swipe = true
}
